name: CI

on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:

# Note, Github Actions is dumb and only steps - not jobs - can access env.
# Therefore, if you update this, make sure to update the deploy job below.
env:
  IS_DEPLOY: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@main

      - name: Install deps
        run: |
          sudo apt update
          sudo apt install gcc-arm-none-eabi binutils-arm-none-eabi

      - name: Compile
        run: sh build.sh

      - name: Install to temp dir
        shell: bash
        run: |
          mkdir TEMPDIR
          sh install.sh TEMPDIR

      - name: Create release archive
        shell: bash
        run: tar -C TEMPDIR/tools/agbcc -czf agbcc.tar.gz bin include lib

      - name: Upload archive
        uses: actions/upload-artifact@main
        with:
          name: agbcc.tar.gz
          path: agbcc.tar.gz

  build-macos:
    runs-on: macos-latest
    steps:

      - name: Checkout
        uses: actions/checkout@main

      - name: Install deps
        run: |
          brew install arm-none-eabi-binutils
          brew install arm-none-eabi-gcc

      - name: Compile
        run: sh build.sh

      - name: Install to temp dir
        shell: bash
        run: |
          mkdir TEMPDIRMAC
          sh install.sh TEMPDIRMAC

      - name: Create release archive
        shell: bash
        run: tar -C TEMPDIR/tools/agbcc -czf agbcc-mac-arm64.tar.gz bin include lib

      - name: Upload archive
        uses: actions/upload-artifact@main
        with:
          name: agbcc-mac-arm64.tar.gz
          path: agbcc-mac-arm64.tar.gz
